export enum RouterNames {
  SO = "SO",
  SO_HOME = "SO_HOME",
  SO_PRODUCT = "SO_PRODUCT",
  SO_CUSTOMER = "SO_CUSTOMER",
  SO_NEW_ORDER = "SO_NEW_ORDER",
  PROFILE = "PROFILE",
  SO_SALE = "SO_SALE",

  LMI = "LMI",
  LMI_HOME = "LMI_HOME",
  LMI_INSTALL_ORDER = "LMI_INSTALL_ORDER",
  LMI_ORDERS = "LMI_ORDERS",
  LMI_ORDER = "LMI_ORDER",

  CORE = "CORE",
  CORE_STATS_BASE = "CORE_STATS_BASE",
  CORE_STATS = "CORE_STATS",
  CORE_STATS_CREATE = "CORE_STATS_CREATE",
  CORE_STATS_EDIT = "CORE_STATS_EDIT",
  CORE_STATS_KPI = "CORE_STATS_KPI",
  CORE_STATS_USERS = "CORE_STATS_USERS",
}
