export enum UserTypeEnum {
  NOTHING = 1,
  SELLER = 2,
  ADMIN_SELLER = 3,
  LAST_MILE_INSTALLER = 4,
  ADMIN_LAST_MILE_INSTALLER = 5,
  EXTERNAL_INSTALLER = 6,
  ADMIN_EXTERNAL_INSTALLER = 7,
  SUPER_ADMIN = 8,
}
